### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by jccastel** [NickButler213/Butler_CSCI2275_FinalProject#1]
Changing random() to rand(), the code compiles, and runs, but there was no obvious output

skipList.cpp: In member function 'int List::levelGenerator()':
skipList.cpp:34:9: error: 'random' was not declared in this scope
  while (random()%2)
         ^~~~~~
skipList.cpp:34:9: note: suggested alternative: 'rand'
  while (random()%2)
         ^~~~~~
         rand

**Comment by NickButler213** [comment]
this only happens in windows, it has been changed to rand() to work in both windows and linux
