### ISSUE TITLE
general comments

### ISSUE THREAD

**Issue by jccastel** [NickButler213/Butler_CSCI2275_FinalProject#2]
Nick, overall I found the concept of the skiplist interesting, and I think you did a good job explaining it in your readme, report, and skiplist .md files. The plots show the efficiency clearly. I had a few suggestions to maybe make those writeups a little more readable for someone not familiar with the concepts. When I tried to compile, I got an error with the random function; it could just be a version thing. Lastly, when I ran the code, there was no obvious output. I’m not sure what to expect in that regard.
-Jon

Writeup suggestions:
Readme, report, skiplist .md files could use some minor proofreading. Also, double check the assignments requirements for the readme file.

In the readme, you have compile instructions, but I suggest adding a line with run instructions and a select input file that you think is optimized for someone to test the code efficiently.

Is the y axis of insert.png supposed to be ms instead of s?

In the readme you state “In the end the skip list will go through all items in order faster, but this project explores if whether the timing of the search, delete, and insert operations make the skip list worth it compared to the BST.” Were you expecting skip list to be faster in the beginning, but in the end, it was slower, but more robust? It might be valuable to state your hypothesis and the final conclusion up front so that it’s clear what your code is showing from the start.

Code was well commented to understand function purpose, but when running the code, there was no obvious output. I wasn’t sure what to expect.

-Jon

**Comment by NickButler213** [comment]
output of driver.cpp file is now specified in README.md
